service: graphql # NOTE: update this with your service name

provider:
  name: openwhisk
  runtime: nodejs:8

functions:
  graphql:
    handler: index.handler
    events:
      - http:
          path: graphql
          method: post

plugins:
  - serverless-openwhisk
